// Generated by CoffeeScript 1.9.0
(function() {
  var checkImage;

  checkImage = require('./checkImage');

  checkImage.checkMedia(__dirname + '/media/test.mp4');

  checkImage.checkMedia(__dirname + '/media/small.mp4');

}).call(this);
