// Generated by CoffeeScript 1.9.0
(function() {
  var Buffer, buffer1, buffer2, sig;

  Buffer = require('buffer').Buffer;

  sig = 'FFD8FF';

  buffer1 = new Buffer(sig, 'hex');

  buffer2 = new Buffer(sig, 'hex');

  console.log(buffer1, ' <-----> ', buffer2);

  console.log(' buffer1 ', Buffer.isBuffer(buffer1));

  console.log('instance', buffer1 instanceof Buffer);

  console.log(buffer1.equals(buffer2));

  console.log(Buffer.compare(buffer1, buffer2));

  throw new Error('silly error');

}).call(this);
